### ISSUE TITLE
Missing files 'computePerfRadius' and 'computeRadius'

### ISSUE THREAD

**Issue by remihndz** [adelphin/vascularTree-CCO#4]
I was trying to see an output of your code by running 'showGraph.m' but it seems (at least) two functions are missing in the repository: computePerfRadius and computeRadius, both called by updateTree.m, line 55 and 57 respectively. 
I just wanted to let you know and if you fix this, I would love to try again this code.

Best regards.

**Comment by adelphin** [comment]
Hi there

The functions are situated in `vascularTree-CCO/mainTreeBuilding/parametersComputation/`
You should make sure that all the subfolders are in your path (I did not implement anything to do that automatically yet).
The way I do it is that I right click on the directory containing the code in the Matlab file explorer, and click "Add to path -> selected folders and subfolders".

Please let me know if that solves your problem :)

**Comment by remihndz** [comment]
My apologies, I had missed this subfolder. Works great, great job.
