### ISSUE TITLE
connected papers

### ISSUE THREAD

**Issue by KunChenUSTC** [adelphin/vascularTree-CCO#5]
Hi, thanks for your excellent work.

I have a question, as you mentioned in the 'Readme.md', two papers were listed as Hamarneth's and Linninger's, however, no links are below them. Especially, I can't find hamarneth's work on google scholar. Can you provide us with links of these works?

Thank you very much!

**Comment by adelphin** [comment]
Hi, thank you for your interest.
I just added the DOIs of the concerned papers. I'm sorry, there was a typo in Hamarneh's name, which did not simplify the task...
Hope it will be fine now.

**Comment by KunChenUSTC** [comment]
Appreciate it, thanks a lot!
